### ISSUE TITLE
:smiley_cat: Milestones Spring21

### ISSUE THREAD

**Issue by Yayka** [flapjs/webapp#36]
### Documentation/wiki
- [ ] on boarding docs
- [ ] JSDocs   

step-by-step guides on:  

  - [ ] deploying
  - [ ] safe rollbacks
  - [ ] Pull Request reviews

### Testing
- [ ] build + deployment tests
- [ ] UI tests (Cypress)]
- [ ] Linter
- [ ] Code coverage tests

### Monitoring
- [ ] Alerts for acute problems 
- [ ] Ticketing
- [ ] Logging

### Bugs
[trello board](https://www.notion.so/71f04954c5d942fdb0919edd0dd6e0e0?v=1a1ca762c8a24c8cb166ad8790bb8185)
